### ISSUE TITLE
qe error

### ISSUE THREAD

**Issue by magiobus** [magiobus/Ejercicio-de-Compilacion#1]
Fer ya subi el q29 solo que el qe no mata el programa me manda al error pero ahi se queda entonces para poder actualizar eso necesitas checar como matar el qe cuando ya muestre que hubo un error en tal lugar. Segun yo si tiene que pasar eso

**Comment by Wolfhergang** [comment]
ya arreglé que el qe mande de regreso a q0, aun es probable que tenga errores pero los ire buscando

**Comment by magiobus** [comment]
ah!!! ya me desespere me estoy haciendo garras netbeans no tiene sentido
para mi fer :( me falta una condicion de <= lo subire y pondre el codigo en
comentario , el que no jala y deberia de

El 14 de abril de 2012 16:16, Fernando Lopez <
reply@reply.github.com
