### ISSUE TITLE
bugs generales 

### ISSUE THREAD

**Issue by magiobus** [magiobus/Ejercicio-de-Compilacion#3]
hola , bugs que encuentren los pueden publicar aqui

BUGS 

: build sucessfull (manda a error pero no tiene mensaje) := id  si funciona
:= numeros ( no funciona con numeros de 1 digito, solo 2+)
-  a que estado debe de mandar ? dice que el q20 , el q20 es de <

**Comment by Wolfhergang** [comment]
el "+" debe mandar a q20, es el "<" el que esta mal, debe mandar a q10

: manda un error pero no tiene mensaje porque nuestra gestion de errores IGNORA los errores y no los mand al resultado, por eso no sale nada con : y con := si, := es asignación y : es un error lexico

Sobre lo del < te encargo que lo arregles, buscare mas bugs.

**Comment by Wolfhergang** [comment]
Hay un bug general en todos los estados de simbolos, si pones 2 veces el simbolo, por ejemplo "  --  "  o " // " ignora el ultimo simbolo y no lo agrega al resultado.

si puedes intenta encontrar el porque
